language: scala
scala:
   - 2.13.2
services:
  - postgresql
#  - mysql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# before_install:
#  - mysql -e 'CREATE DATABASE travis_ci_test;'  

script:
- sbt test
- sbt '; set javaOptions += "-Ddb-url=postgresql://postgres:travis@localhost:5432/travis_ci_test" ; jdbc/it:test '
#- sbt '; set javaOptions += "-Ddb-url=mysql://localhost:3306/travis_ci_test" ; jdbc/it:test '
