language: scala
scala:
   - 2.13.2
services:
  - docker

before_install:
- docker pull postgres/latest
- docker run --rm -P -p 127.0.0.1:15432:5432 -e POSTGRES_PASSWORD="travis" --name pg-db-proto postgres:latest
- docker ps -a

script:
- sbt test
- sbt '; set javaOptions += "-Ddb-url=postgresql://postgres:travis@localhost:15432/postgres" ; jdbc/it:test '
